# Generated by Django 3.2.2 on 2021-05-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_alter_dealer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='LucknowArea',
        ),
        migrations.RenameModel(
            old_name='Dealer',
            new_name='LucknowDealer',
        ),
    ]
