# Generated by Django 3.2.2 on 2021-05-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0007_lucknowbeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanpurDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
