# Generated by Django 3.2.2 on 2021-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0008_kanpurdealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delhibeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital', models.CharField(max_length=200)),
                ('With_Oxygen', models.CharField(max_length=200)),
                ('Without_Oxygen', models.CharField(max_length=200)),
            ],
        ),
    ]
