# Generated by Django 3.2.2 on 2021-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0009_delhibeds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delhibeds',
            old_name='With_Oxygen',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='delhibeds',
            old_name='Without_Oxygen',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='delhibeds',
            name='Vacant',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
