# Generated by Django 3.2.2 on 2021-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0010_auto_20210522_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanpurbeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('centre', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
            ],
        ),
    ]
